spring:
   datasource:
      url: jdbc:postgresql://192.168.56.2:5432/activiti
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
   jpa.hibernate.ddl-auto: update